#!/usr/bin/env node

/**
 * Phase 2 calibration export workflow.
 *
 * Generates environment-scoped QUANTUM_ALERT_* / QUANTUM_SLO_* .env packs from
 * /api/quantum/providers/reliability-calibration.
 */

const fs = require('fs/promises');
const path = require('path');
const axios = require('axios');

const DEFAULT_BASE_URL = process.env.BACKEND_PUBLIC_URL || process.env.BACKEND_URL || 'http://localhost:3001';
const DEFAULT_OUTPUT_DIR = path.resolve(__dirname, '..', 'calibration', 'quantum');
const DEFAULT_ENVIRONMENTS = ['dev', 'staging', 'prod'];
const DEFAULT_MIN_APPROVAL_CONFIDENCE = String(process.env.QUANTUM_CALIBRATION_APPROVAL_MIN_CONFIDENCE || 'medium').toLowerCase();
const DEFAULT_SOURCE = normalizeSourceTag(process.env.QUANTUM_RELIABILITY_COLLECTOR_SOURCE || '');
const DEFAULT_SOURCE_BY_ENV = parseSourceByEnv(process.env.QUANTUM_RELIABILITY_COLLECTOR_SOURCE_BY_ENV || '');

const ENV_PROFILE_DEFAULTS = {
  dev: {
    lookback_minutes: 120,
    bucket_seconds: 60,
    min_buckets: 8,
  },
  staging: {
    lookback_minutes: 360,
    bucket_seconds: 60,
    min_buckets: 10,
  },
  prod: {
    lookback_minutes: 1440,
    bucket_seconds: 120,
    min_buckets: 12,
  },
};

function parseArgs(argv = []) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      continue;
    }

    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      args[key] = true;
      continue;
    }

    args[key] = next;
    i += 1;
  }
  return args;
}

function toPositiveInt(value, fallback, min = 1, max = Number.MAX_SAFE_INTEGER) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  return Math.min(Math.max(Math.round(numeric), min), max);
}

function parseList(rawValue, fallback = []) {
  const value = String(rawValue || '').trim();
  if (!value) {
    return fallback;
  }
  return value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function normalizeSourceTag(value) {
  const normalized = String(value || '').trim().toLowerCase();
  return normalized || null;
}

function parseSourceByEnv(rawValue) {
  const output = {};
  const parts = parseList(rawValue, []);
  parts.forEach((entry) => {
    const separatorIndex = entry.indexOf(':');
    if (separatorIndex <= 0) {
      return;
    }
    const envName = String(entry.slice(0, separatorIndex)).trim().toLowerCase();
    const source = normalizeSourceTag(entry.slice(separatorIndex + 1));
    if (!envName || !source) {
      return;
    }
    output[envName] = source;
  });
  return output;
}

function resolveSourceForEnvironment(environment, defaultSource, sourceByEnv) {
  const envKey = String(environment || '').trim().toLowerCase();
  if (!envKey) {
    return defaultSource || null;
  }
  return sourceByEnv[envKey] || defaultSource || null;
}

function confidenceRank(level = 'low') {
  const normalized = String(level || '').trim().toLowerCase();
  if (normalized === 'high') return 3;
  if (normalized === 'medium') return 2;
  return 1;
}

function isConfidenceApproved(level, minimumLevel) {
  return confidenceRank(level) >= confidenceRank(minimumLevel);
}

function toNumericEnvValue(value, fallback = 0, precision = 6) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return Number(fallback);
  }

  if (Number.isInteger(numeric)) {
    return numeric;
  }

  return Number(numeric.toFixed(precision));
}

function normalizeEnvOverrides(overrides = {}) {
  return {
    QUANTUM_ALERT_VQE_QUEUE_LENGTH: toPositiveInt(overrides.QUANTUM_ALERT_VQE_QUEUE_LENGTH, 20, 1, 5000),
    QUANTUM_ALERT_DWAVE_QUEUE_LENGTH: toPositiveInt(overrides.QUANTUM_ALERT_DWAVE_QUEUE_LENGTH, 25, 1, 5000),
    QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT: toNumericEnvValue(overrides.QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT, 1.2, 6),
    QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT: toNumericEnvValue(overrides.QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT, 1.6, 6),
    QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET: toNumericEnvValue(overrides.QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET, 99, 6),
  };
}

function formatEnvPack({
  environment,
  approved,
  confidence,
  minimumConfidence,
  source,
  sampleSource,
  generatedAt,
  query,
  envOverrides,
}) {
  const decision = approved ? 'approved' : 'review_required';

  return [
    '# Auto-generated by export_quantum_calibration_env.js',
    `# Generated at: ${generatedAt}`,
    `# Environment: ${environment}`,
    `# Confidence: ${confidence} (minimum required: ${minimumConfidence})`,
    `# Approval: ${decision}`,
    `# Source: ${source}`,
    `# Sample source tag: ${sampleSource || 'all'}`,
    `# Inputs: lookback_minutes=${query.lookback_minutes}, bucket_seconds=${query.bucket_seconds}, min_buckets=${query.min_buckets}, source=${sampleSource || 'all'}`,
    '',
    `QUANTUM_ALERT_VQE_QUEUE_LENGTH=${envOverrides.QUANTUM_ALERT_VQE_QUEUE_LENGTH}`,
    `QUANTUM_ALERT_DWAVE_QUEUE_LENGTH=${envOverrides.QUANTUM_ALERT_DWAVE_QUEUE_LENGTH}`,
    `QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT=${envOverrides.QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT}`,
    `QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT=${envOverrides.QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT}`,
    `QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET=${envOverrides.QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET}`,
    '',
  ].join('\n');
}

async function fetchCalibration(client, query) {
  const response = await client.get('/api/quantum/providers/reliability-calibration', { params: query });
  return response?.data?.data || {};
}

function usage() {
  return `Usage:\n  node scripts/export_quantum_calibration_env.js [options]\n\nOptions:\n  --base-url <url>              Backend base URL (default: ${DEFAULT_BASE_URL})\n  --environments <csv>          Env list: dev,staging,prod\n  --output-dir <path>           Output folder for generated packs\n  --source <tag>                Filter calibration input by reliability source tag\n  --source-by-env <csv>         Per-env source mapping (ex: dev:collector-dev,prod:collector-prod)\n  --lookback-minutes <n>        Override lookback_minutes for all environments\n  --bucket-seconds <n>          Override bucket_seconds for all environments\n  --min-buckets <n>             Override min_buckets for all environments\n  --min-confidence <level>      low | medium | high (default: ${DEFAULT_MIN_APPROVAL_CONFIDENCE})\n  --fail-on-unapproved          Exit non-zero when any environment is review_required\n  --help                        Show this help\n`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    process.stdout.write(usage());
    return;
  }

  const baseUrl = String(args['base-url'] || DEFAULT_BASE_URL).replace(/\/+$/, '');
  const outputDir = path.resolve(process.cwd(), String(args['output-dir'] || DEFAULT_OUTPUT_DIR));
  const environmentNames = parseList(args.environments, DEFAULT_ENVIRONMENTS);
  const minConfidence = String(args['min-confidence'] || DEFAULT_MIN_APPROVAL_CONFIDENCE).toLowerCase();
  const failOnUnapproved = Boolean(args['fail-on-unapproved']);
  const defaultSource = normalizeSourceTag(args.source || DEFAULT_SOURCE);
  const sourceByEnv = {
    ...DEFAULT_SOURCE_BY_ENV,
    ...parseSourceByEnv(args['source-by-env']),
  };

  const globalOverrides = {
    lookback_minutes: args['lookback-minutes'] !== undefined
      ? toPositiveInt(args['lookback-minutes'], 120, 1, 60 * 24 * 14)
      : null,
    bucket_seconds: args['bucket-seconds'] !== undefined
      ? toPositiveInt(args['bucket-seconds'], 60, 10, 60 * 60 * 12)
      : null,
    min_buckets: args['min-buckets'] !== undefined
      ? toPositiveInt(args['min-buckets'], 8, 2, 240)
      : null,
  };

  await fs.mkdir(outputDir, { recursive: true });

  const client = axios.create({
    baseURL: baseUrl,
    timeout: 20000,
    validateStatus: (status) => status >= 200 && status < 500,
  });

  const manifest = {
    generated_at: new Date().toISOString(),
    base_url: baseUrl,
    output_dir: outputDir,
    minimum_confidence: minConfidence,
    environments: [],
  };

  for (const envName of environmentNames) {
    const profileDefaults = ENV_PROFILE_DEFAULTS[envName] || ENV_PROFILE_DEFAULTS.dev;
    const query = {
      lookback_minutes: globalOverrides.lookback_minutes ?? profileDefaults.lookback_minutes,
      bucket_seconds: globalOverrides.bucket_seconds ?? profileDefaults.bucket_seconds,
      min_buckets: globalOverrides.min_buckets ?? profileDefaults.min_buckets,
      include_windows: false,
    };
    const sampleSource = resolveSourceForEnvironment(envName, defaultSource, sourceByEnv);
    if (sampleSource) {
      query.source = sampleSource;
    }

    const filePath = path.join(outputDir, `${envName}.quantum-calibration.env`);

    try {
      const calibration = await fetchCalibration(client, query);
      const confidence = String(calibration?.confidence?.level || 'low').toLowerCase();
      const source = String(calibration?.recommendations?.source || 'unknown');
      const envOverrides = normalizeEnvOverrides(calibration?.recommendations?.env_overrides || {});
      const approved = isConfidenceApproved(confidence, minConfidence);

      await fs.writeFile(filePath, formatEnvPack({
        environment: envName,
        approved,
        confidence,
        minimumConfidence: minConfidence,
        source,
        sampleSource,
        generatedAt: new Date().toISOString(),
        query,
        envOverrides,
      }), 'utf8');

      manifest.environments.push({
        environment: envName,
        status: approved ? 'approved' : 'review_required',
        confidence,
        source,
        sample_source: sampleSource,
        query,
        env_file: filePath,
        sample_counts: calibration?.sample_counts || {},
        env_overrides: envOverrides,
      });
    } catch (error) {
      const envOverrides = normalizeEnvOverrides({});
      await fs.writeFile(filePath, formatEnvPack({
        environment: envName,
        approved: false,
        confidence: 'low',
        minimumConfidence: minConfidence,
        source: 'calibration-request-failed',
        sampleSource,
        generatedAt: new Date().toISOString(),
        query,
        envOverrides,
      }), 'utf8');

      manifest.environments.push({
        environment: envName,
        status: 'error',
        confidence: 'low',
        source: 'calibration-request-failed',
        sample_source: sampleSource,
        query,
        env_file: filePath,
        error: String(error?.message || error),
        env_overrides: envOverrides,
      });
    }
  }

  const manifestPath = path.join(outputDir, 'manifest.json');
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

  const approvedCount = manifest.environments.filter((item) => item.status === 'approved').length;
  const reviewCount = manifest.environments.length - approvedCount;

  process.stdout.write(
    `Generated ${manifest.environments.length} calibration packs in ${outputDir}. Approved: ${approvedCount}, review required/error: ${reviewCount}.\n`
  );
  process.stdout.write(`Manifest: ${manifestPath}\n`);

  if (failOnUnapproved && reviewCount > 0) {
    process.exitCode = 1;
  }
}

main().catch((error) => {
  process.stderr.write(`Calibration export failed: ${error.message}\n`);
  process.exit(1);
});
