#!/usr/bin/env node

/**
 * Promote exported quantum calibration packs into deployment-ready env files.
 *
 * Expected input: manifest generated by export_quantum_calibration_env.js
 */

const fs = require('fs/promises');
const path = require('path');

const DEFAULT_MANIFEST_PATH = path.resolve(__dirname, '..', 'calibration', 'quantum', 'manifest.json');

function parseArgs(argv = []) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      continue;
    }

    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      args[key] = true;
      continue;
    }

    args[key] = next;
    i += 1;
  }
  return args;
}

function parseEnvLines(content = '') {
  const result = {};
  const lines = String(content || '').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex <= 0) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();
    if (!key) {
      continue;
    }
    result[key] = value;
  }
  return result;
}

function resolvePathFromBase(targetPath, baseDir) {
  const raw = String(targetPath || '').trim();
  if (!raw) {
    return '';
  }
  if (path.isAbsolute(raw)) {
    return raw;
  }
  return path.resolve(baseDir, raw);
}

function normalizeMode(value) {
  const normalized = String(value || 'strict').trim().toLowerCase();
  if (normalized === 'allow-review') {
    return 'allow-review';
  }
  return 'strict';
}

function usage() {
  return `Usage:\n  node scripts/promote_quantum_calibration_pack.js --environment <env> [options]\n\nOptions:\n  --environment <name>        Environment key from manifest (required)\n  --manifest <path>           Manifest path (default: ${DEFAULT_MANIFEST_PATH})\n  --mode <strict|allow-review> Promotion mode (default: strict)\n  --output-file <path>        Output env file path\n  --report-file <path>        Output report json path\n  --help                      Show this help\n`;
}

function buildOutputContent({
  environment,
  sourceFile,
  mode,
  status,
  confidence,
  source,
  query,
  overrides,
}) {
  return [
    '# Auto-generated by promote_quantum_calibration_pack.js',
    `# Generated at: ${new Date().toISOString()}`,
    `# Environment: ${environment}`,
    `# Mode: ${mode}`,
    `# Source manifest status: ${status}`,
    `# Confidence: ${confidence}`,
    `# Calibration source: ${source}`,
    `# Source env pack: ${sourceFile}`,
    `# Query: lookback_minutes=${query.lookback_minutes}, bucket_seconds=${query.bucket_seconds}, min_buckets=${query.min_buckets}`,
    '',
    `QUANTUM_ALERT_VQE_QUEUE_LENGTH=${overrides.QUANTUM_ALERT_VQE_QUEUE_LENGTH}`,
    `QUANTUM_ALERT_DWAVE_QUEUE_LENGTH=${overrides.QUANTUM_ALERT_DWAVE_QUEUE_LENGTH}`,
    `QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT=${overrides.QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT}`,
    `QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT=${overrides.QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT}`,
    `QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET=${overrides.QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET}`,
    '',
  ].join('\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    process.stdout.write(usage());
    return;
  }

  const environment = String(args.environment || '').trim();
  if (!environment) {
    process.stderr.write('Missing required option: --environment\n');
    process.stderr.write(usage());
    process.exit(1);
    return;
  }

  const mode = normalizeMode(args.mode);
  const manifestPath = path.resolve(process.cwd(), String(args.manifest || DEFAULT_MANIFEST_PATH));
  const manifestDir = path.dirname(manifestPath);

  const manifestRaw = await fs.readFile(manifestPath, 'utf8');
  const manifest = JSON.parse(manifestRaw);
  const environments = Array.isArray(manifest?.environments) ? manifest.environments : [];

  const entry = environments.find((item) => String(item?.environment || '').trim() === environment);
  if (!entry) {
    process.stderr.write(`Environment ${environment} not found in manifest: ${manifestPath}\n`);
    process.exit(1);
    return;
  }

  if (mode === 'strict' && String(entry.status || '').trim() !== 'approved') {
    process.stderr.write(
      `Refusing promotion for ${environment}: manifest status is ${entry.status || 'unknown'} (strict mode).\n`
    );
    process.exit(1);
    return;
  }

  const sourceFile = resolvePathFromBase(entry.env_file, manifestDir);
  if (!sourceFile) {
    process.stderr.write(`Manifest entry has no env_file for environment ${environment}.\n`);
    process.exit(1);
    return;
  }

  const sourceContent = await fs.readFile(sourceFile, 'utf8');
  const parsedEnv = parseEnvLines(sourceContent);

  const requiredKeys = [
    'QUANTUM_ALERT_VQE_QUEUE_LENGTH',
    'QUANTUM_ALERT_DWAVE_QUEUE_LENGTH',
    'QUANTUM_ALERT_VQE_ERROR_RATE_PERCENT',
    'QUANTUM_ALERT_DWAVE_ERROR_RATE_PERCENT',
    'QUANTUM_SLO_PROVIDER_AVAILABILITY_TARGET',
  ];

  const missingKeys = requiredKeys.filter((key) => !Object.prototype.hasOwnProperty.call(parsedEnv, key));
  if (missingKeys.length > 0) {
    process.stderr.write(`Cannot promote ${environment}: missing keys in source env pack: ${missingKeys.join(', ')}\n`);
    process.exit(1);
    return;
  }

  const outputFile = path.resolve(
    process.cwd(),
    String(args['output-file'] || path.join(manifestDir, 'promoted', `${environment}.quantum-approved.env`))
  );
  const reportFile = path.resolve(
    process.cwd(),
    String(args['report-file'] || `${outputFile}.report.json`)
  );

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.mkdir(path.dirname(reportFile), { recursive: true });

  const outputContent = buildOutputContent({
    environment,
    sourceFile,
    mode,
    status: String(entry.status || 'unknown'),
    confidence: String(entry.confidence || 'unknown'),
    source: String(entry.source || 'unknown'),
    query: entry.query || {},
    overrides: parsedEnv,
  });
  await fs.writeFile(outputFile, outputContent, 'utf8');

  const reportPayload = {
    generated_at: new Date().toISOString(),
    mode,
    environment,
    manifest_path: manifestPath,
    source_env_file: sourceFile,
    output_file: outputFile,
    output_status: mode === 'strict' ? 'approved' : String(entry.status || 'unknown'),
    manifest_entry: {
      status: entry.status || 'unknown',
      confidence: entry.confidence || 'unknown',
      source: entry.source || 'unknown',
      query: entry.query || {},
      sample_counts: entry.sample_counts || {},
    },
    overrides: requiredKeys.reduce((acc, key) => {
      acc[key] = parsedEnv[key];
      return acc;
    }, {}),
  };

  await fs.writeFile(reportFile, `${JSON.stringify(reportPayload, null, 2)}\n`, 'utf8');

  process.stdout.write(`Promoted ${environment} calibration pack to ${outputFile}\n`);
  process.stdout.write(`Report: ${reportFile}\n`);
}

main().catch((error) => {
  process.stderr.write(`Calibration promotion failed: ${error.message}\n`);
  process.exit(1);
});
